parameters:
#    stc_event.example.class: STC\EventBundle\Example

services:
#    stc_event.example:
#        class: %stc_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
