imports:
    - { resource: parameters.yml }
    - { resource: security.yml }


    # Mopa Bootstrap


    # FriendOfSymfony Bundles
    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }

    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_intl.yml }

    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }

framework:
    #esi:                   ~
    translator:
        fallback:           en
    secret:                 %secret%
    router:
        resource:           "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:                    true
    csrf_protection:         true
    validation:
        enable_annotations:  true
    templating:
        engines:             ['twig']
        #assets_version:      SomeVersionScheme

    default_locale:          %locale%
    session:
        save_path:           %kernel.root_dir%/cache/sessions

    fragments:               ~
    trusted_proxies:         ~
    http_method_override:    true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:   %database_driver%
                dbname:   %database_name%
                user:     %database_user%
                host:     %database_host%
                password: %database_password%

        types:
            json:     Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default

        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

jms_serializer:
    metadata:
        directories:
            - { path: %kernel.root_dir%/../vendor/sonata-project/user-bundle/Sonata/UserBundle/Resources/config/serializer/FOSUserBundle, namespace_prefix: 'FOS\UserBundle' }

# Assetic Configuration
#assetic:
#    debug:          %kernel.debug%
#    use_controller: false
#    filters:
#        cssrewrite: ~
#        # closure:
#        #     jar: %kernel.root_dir%/java/compiler.jar
#        # yui_css:
#        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
#
#        # Comment out those lines if you wish to use the less version of bootstrap
#        less:
#            node: /usr/local/bin/node
#            node_paths: [/usr/local/node/node-v0.10.22/lib/node_modules]
#            apply_to: "\.less$"

nelmio_api_doc: ~

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters:  true }

stof_doctrine_extensions:
   default_locale: "%locale%"
   orm:
       default:
           timestampable: true
           loggable: true
           translatable: true
           blameable: true
           sluggable: true
