home:
    pattern:  /
    defaults: { _controller: STCSiteBundle:Site:home }

symfonyTn:
    pattern:  /symfony-tn
    defaults: { _controller: STCSiteBundle:Site:symfonyTn }

whoWeAre:
    pattern:  /who-we-are
    defaults: { _controller: STCSiteBundle:Site:whoWeAre }

copyright:
    pattern:  /copyright
    defaults: { _controller: STCSiteBundle:Site:copyright }
